# -*- coding: utf-8 -*-
r"""
Tiling of the plane by isometric copies of a polygon

EXAMPLES::

    sage: F = AffineGroup(2, AA)
    sage: F([1,2,3,4],[5,6])
          [1 2]     [5]
    x |-> [3 4] x + [6]

AUTHORS:

 - Fait avec Lucas <lfx337@gmail.com>, le 28 novembre 2024.

"""
#*****************************************************************************
#       Copyright (C) 2024 Sébastien Labbé <slabqc@gmail.com>
#
#  Distributed under the terms of the GNU General Public License version 2 (GPLv2)
#
#  The full text of the GPLv2 is available at:
#
#                  http://www.gnu.org/licenses/
#*****************************************************************************
from sage.groups.affine_gps.affine_group import AffineGroup

class PolygonTiling:
    r"""
    A periodic tiling by one polygon

    TODO::

    - It would maybe be better to use polyhedron instead of list of
      vertices?

    - Use the graph Eulerian paths and add a tikz method.

    - Code more (all?) of the 15 pentagons
    """
    def __init__(self, polygon, patch_symmetries=None, translations=None, ring=None):
        r"""

        If ``T`` denotes the group generated by the translations, then
        the input must be such that

            ``[t*s(polygon) for s in patch_symmetries for t in T]``

        is a tiling of the space.

        INPUT:

        - ``polygon`` -- list of vertices
        - ``patch_symmetries`` -- list of transformations (affine maps)
        - ``translations`` -- list of translations (affine maps),
          generators of a subgroup of translations
        - ``ring`` -- ring (default:``None``), if ``None``, then is uses ``AA``

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: F = AffineGroup(2, AA)
            sage: T = [F.translation((1,0))]
            sage: J = PolygonTiling(jennifer, translations=T)
            sage: J
            Tiling by the polygon [(0, 0), (1, 0), (2.732050807568878?,
            1), (1.866025403784439?, 3/2), (0, 1)]

        """
        if ring is None:
            from sage.rings.qqbar import AA
            ring = AA

        from sage.modules.free_module_element import vector
        self._polygon = [vector(ring, p) for p in polygon]

        if not self._polygon:
            raise ValueError('polygon(={}) must be non empty'.format(self._polygon))

        self._dimension = len(self._polygon[0])
        self._affine_group = AffineGroup(self._dimension, ring)

        if patch_symmetries is None:
            self._patch_symmetries = [self._affine_group.one()]
        else:
            self._patch_symmetries = patch_symmetries

        if translations is None:
            self._translations = [self._affine_group.one()]
        else:
            self._translations = translations

    def __repr__(self):
        r"""
        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: J
            Tiling by the polygon [(0, 0), (1, 0), (2.732050807568878?,
            1), (1.866025403784439?, 3/2), (0, 1)]

        """
        return "Tiling by the polygon {}".format(self._polygon)

    def affine_group(self):
        r"""
        Return the affine group containing the isometries

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: J.affine_group()
            Affine Group of degree 2 over Algebraic Real Field

        """
        return self._affine_group

    def dimension(self):
        r"""
        Return the dimension of the space

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: J.dimension()
            2

        """
        return self._dimension

    def polygon_vertex_distances(self):
        r"""
        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: J.polygon_vertex_distances()
            [1, 2.000000000000000?, 1.000000000000000?, 1.931851652578137?, 1]

        """
        N = len(self._polygon)
        distances = []
        for i in range(N):
            p = self._polygon[i]
            q = self._polygon[(i+1)%N]
            v = q - p
            distances.append(v.norm())
        return distances

    def patch(self):
        r"""
        Return a list of list of vertices.

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: list(J.patch())
            [[(0, 0),
              (1, 0),
              (2.732050807568878?, 1),
              (1.866025403784439?, 1.5000000000000000?),
              (0, 1)]]

        """
        for s in self._patch_symmetries:
            yield [s*v for v in self._polygon] 

    def iter_polygons(self, depth):
        r"""
        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: F = AffineGroup(2, AA)
            sage: T = [F.translation((1,0))]
            sage: J = PolygonTiling(jennifer, translations=T)
            sage: list(J.iter_polygons(depth=2))
            [[(-2, 0), (-1, 0), (sqrt(3) - 1, 1), (1/2*sqrt(3) - 1, 3/2), (-2, 1)],
             [(-1, 0), (0, 0), (sqrt(3), 1), (1/2*sqrt(3), 3/2), (-1, 1)],
             [(0, 0), (1, 0), (sqrt(3) + 1, 1), (1/2*sqrt(3) + 1, 3/2), (0, 1)],
             [(1, 0), (2, 0), (sqrt(3) + 2, 1), (1/2*sqrt(3) + 2, 3/2), (1, 1)]]

        """
        import itertools
        from sage.misc.misc_c import prod
        k = len(self._translations)
        for r in itertools.product(range(-depth, depth), repeat=k):
            t_r = prod(t**ri for (t,ri) in zip(self._translations, r))
            for polygon in self.patch():
                yield [t_r*v for v in polygon] 

    def vertices(self, depth):
        r"""
        Return the set of vertices of the tiling.

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: J.vertices(1)
            {(0, 0), (0, 1), (1, 0), (1/2*sqrt(3) + 1, 3/2), (sqrt(3) + 1, 1)}
            sage: sorted(v.n() for v in J.vertices(1))        # abs tol 0.0001
            [(0.000000000000000, 0.000000000000000),
             (0.000000000000000, 1.00000000000000),
             (1.00000000000000, 0.000000000000000),
             (1.86602540378444, 1.50000000000000),
             (2.73205080756888, 1.00000000000000)]

        """
        s = set()
        for p in self.iter_polygons(depth):
            for v in p:
                v.set_immutable()
                s.add(v)
        return s

    def plot(self, depth):
        r"""
        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: J = PolygonTiling(jennifer)
            sage: J.plot(1)
            Graphics object consisting of 2 graphics primitives


        ::

            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: F = AffineGroup(2, AA)
            sage: patch_symmetries = [F.one(), F.translation((2,2))]
            sage: J = PolygonTiling(jennifer, patch_symmetries)
            sage: J.plot(1)
            Graphics object consisting of 4 graphics primitives

        ::

            sage: jennifer = [(0,0), (1,0), (1+sqrt(3),1), (1+sqrt(3)/2,3/2), (0,1)]
            sage: F = AffineGroup(2, AA)
            sage: T = [F.translation((1,0))]
            sage: J = PolygonTiling(jennifer, translations=T)
            sage: J.plot(1)
            Graphics object consisting of 2 graphics primitives

        """
        from sage.plot.graphics import Graphics
        from sage.plot.polygon import polygon2d
        G = Graphics()
        for p in self.iter_polygons(depth):
            G += polygon2d(p, fill=False, thickness=4, color='orange')
        return G

    def polygons_restricted_to_region(self, region):
        r"""
        Return the recursively enumerated set of polygons that lie inside a
        convex region.

        INPUT:

        - ``region`` -- polyhedron, ideally it should contain entirely the initial
          patch of polygons

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: domino = [(0,0), (2,0), (2,1), (0,1)]
            sage: F = AffineGroup(2, ZZ)
            sage: T = [F.translation((2,0)), F.translation((1,1))]
            sage: J = PolygonTiling(domino, translations=T)
            sage: box = polytopes.hypercube(dim=2, intervals=[(-3,3), (-2,4)])
            sage: J.polygons_restricted_to_region(box)
            A recursively enumerated set with a symmetric structure (breadth first search)

        TODO:

        - Very slow compare to ``iter_polygons`` with a large enough depth
          to be filtered inside a box.

        """
        from sage.sets.recursively_enumerated_set import RecursivelyEnumeratedSet

        seeds = []
        for polygon in self.patch():
            P = tuple(sorted(v for v in polygon))
            for p in P: p.set_immutable()
            seeds.append(P)

        def successors(polygon):
            for t in self._translations:
                P = tuple(sorted(t*v for v in polygon))
                if all(p in region for p in P):
                    for p in P: p.set_immutable()
                    yield P
                t_inv = t.inverse()
                P = tuple(sorted(t_inv*v for v in polygon))
                if all(p in region for p in P):
                    for p in P: p.set_immutable()
                    yield P

        return RecursivelyEnumeratedSet(seeds, successors, structure='symmetric')

    def plot_polygons_restricted_to_region(self, region):
        r"""
        Return a graphics of the polygons that lie inside a convex region.

        INPUT:

        - ``region`` -- polyhedron

        EXAMPLES::

            sage: from slabbe.polygon_tiling import PolygonTiling
            sage: domino = [(0,0), (2,0), (2,1), (0,1)]
            sage: F = AffineGroup(2, ZZ)
            sage: T = [F.translation((2,0)), F.translation((1,1))]
            sage: J = PolygonTiling(domino, translations=T)
            sage: box = polytopes.hypercube(dim=2, intervals=[(-3,3), (-2,4)])
            sage: J.plot_polygons_restricted_to_region(box)
        """
        from sage.plot.graphics import Graphics
        from sage.plot.polygon import polygon2d
        from sage.geometry.polyhedron.plot import cyclic_sort_vertices_2d
        from sage.geometry.polyhedron.constructor import Polyhedron

        R = self.polygons_restricted_to_region(region)
        G = Graphics()
        for p in R:
            p = cyclic_sort_vertices_2d(Polyhedron(p).vertices())
            G += polygon2d(p, fill=False, thickness=4, color='orange')
        return G

def symmetrie(p1, p2):
    r"""
    Return la transformation lineraire qui fait la symmetrie dans la droite
    passant par p1 et p2.
    
    EXAMPLES::

        sage: from slabbe.polygon_tiling import symmetrie
        sage: p1 = (12,166)
        sage: p2 = (45,227)
        sage: T = symmetrie(p1, p2)
        sage: T
              [-1316/2405  2013/2405]     [-289506/2405]
        x |-> [ 2013/2405  1316/2405] x + [ 156618/2405]
        sage: T(p1)
        (12, 166)
        sage: T(p2)
        (45, 227)

    """
    from sage.matrix.constructor import matrix
    from sage.rings.qqbar import AA
    F = AffineGroup(2, AA)
    F_p1 = F.translation(p1)
    (x2,y2) = F_p1.inverse()(p2)
    F_rotate_p2 = F(matrix.column([(x2,y2),(-y2,x2)]))
    F_symmetry = F(matrix.column([(1,0),(0,-1)]))
    T = (F_p1 * F_rotate_p2 * F_symmetry * F_rotate_p2.inverse() * F_p1.inverse())
    assert tuple(p1) == tuple(T(p1)), "{} == {}".format(p1, T(p1))
    assert tuple(p2) == tuple(T(p2)), "{} == {}".format(p2, T(p2))
    return T

def symmetrie_mediatrice(p1, p2):
    r"""
    Return la transformation lineraire qui fait la symmetrie dans la
    mediatrice du segment passant par p1 et p2.
    
    EXAMPLES::

        sage: from slabbe.polygon_tiling import symmetrie_mediatrice
        sage: p1 = (12,166)
        sage: p2 = (45,227)
        sage: T = symmetrie_mediatrice(p1, p2)
        sage: T
              [ 1316/2405 -2013/2405]     [426591/2405]
        x |-> [-2013/2405 -1316/2405] x + [788547/2405]
        sage: T(p1)
        (45, 227)
        sage: T(p2)
        (12, 166)

    """
    from sage.matrix.constructor import matrix
    from sage.rings.qqbar import AA
    F = AffineGroup(2, AA)
    F_p1 = F.translation(p1)
    (x2,y2) = F_p1.inverse()(p2)
    F_rotate_p2 = F(matrix.column([(x2,y2),(-y2,x2)]))
    F_symmetry = F(matrix.column([(-1,0),(0,1)]),(1,0))
    T = (F_p1 * F_rotate_p2 * F_symmetry * F_rotate_p2.inverse() * F_p1.inverse())
    assert tuple(p2) == tuple(T(p1)), "{} == {}".format(p2, T(p1))
    assert tuple(p1) == tuple(T(p2)), "{} == {}".format(p1, T(p2))
    return T

def Jennifer():
    r"""
    EXAMPLES::

        sage: from slabbe.polygon_tiling import Jennifer
        sage: Jennifer()
        Tiling by the polygon [(0, 0), (1, 0), (1.866025403784439?, 1/2),
        (2.732050807568878?, 1), (1.866025403784439?, 3/2), (0, 1)]

    """
    import itertools
    from sage.misc.functional import sqrt
    from sage.rings.rational_field import QQ
    from sage.rings.qqbar import AA
    A = (0,0) 
    B1 = (1,0)
    B2 = (1+sqrt(3)/2,QQ(1/2))
    C = (1+sqrt(3),1)
    D = (1+sqrt(3)/2,QQ(3/2))
    E = (0,1)
    jennifer = [A, B1, B2, C, D, E]

    # transformations
    F = AffineGroup(2, AA)
    rotate30 = F([sqrt(3)/2,QQ(1/2),-QQ(1/2),sqrt(3)/2])
    exchange_xy = F([0,1,1,0])

    patch3 = [F.one(), 
              #rotate30,
              F.translation(D)*rotate30*exchange_xy,
              symmetrie(D, E),
              ]

    g = F.translation((-QQ(1/2), sqrt(3)/2 + 1))
    patch6 = [t for t in patch3]
    patch6.extend(g*rotate30.inverse()*exchange_xy*t for t in patch3)

    #h1 = (sqrt(3)*3/2 + QQ(3/2), sqrt(3)/2 + QQ(5/2))
    #h2 = (sqrt(3)*3/2 + QQ(3/2), sqrt(3)/2 + QQ(3/2))
    #h1 = (sqrt(3)/2 - QQ(1/2), sqrt(3)*3/2 + QQ(7/2))
    h1 = (-QQ(1/2), sqrt(3)*3/2 + 4)
    h2 = (sqrt(3)/2 - QQ(1/2), sqrt(3)*3/2 + QQ(9/2))
    h  = symmetrie(h1, h2)
    hm = symmetrie_mediatrice(h1, h2)
    patch12 = [t for t in patch6]
    patch12.extend(hm*h*t for t in patch6)

    t1 = F.translation((sqrt(3)/2 + QQ(1/2), sqrt(3)/2 + QQ(3/2)))
    t2 = F.translation((-5*sqrt(3)/2 - 4, 2*sqrt(3) + QQ(9/2)))
    translations = [t1,t2]

    J = PolygonTiling(jennifer, patch12, translations)
    return J

#J = Jennifer()


